package util

import (
	"bufio"
	"fmt"
	"math/rand"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/fatih/color"
)

// CHA map
const CHA = "abcdefghijklmnopqrstuvwxyz0123456789"

// RandString n is the length. a-z 0-9
func RandString(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = CHA[rand.Intn(len(CHA))]
	}
	return string(b)
}

// Scanline scan line
func Scanline() string {
	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		return scanner.Text()
	}
	fmt.Println("\nInterrupted.")
	os.Exit(1)
	return ""
}

// ScanlineTrim scan line and trim
func ScanlineTrim() string {
	return strings.TrimSpace(Scanline())
}

// ChooseIndex return valid index in [0, maxLen)
func ChooseIndex(maxLen int) int {
	color.Cyan("Please choose one (index): ")
	for {
		index := ScanlineTrim()
		i, err := strconv.Atoi(index)
		if err == nil && i >= 0 && i < maxLen {
			return i
		}
		color.Red("Invalid index! Please try again: ")
	}
}

// YesOrNo must choose one
func YesOrNo(note string) bool {
	color.Cyan(note)
	for {
		tmp := ScanlineTrim()
		if tmp == "y" || tmp == "Y" {
			return true
		}
		if tmp == "n" || tmp == "N" {
			return false
		}
		color.Red("Invalid input. Please input again: ")
	}
}

var fmtReg = regexp.MustCompile(`<span\sclass=["']?verdict-format-([\S^>]+?)["']?>.*?</span>`)
var colReg = regexp.MustCompile(`<span\sclass=["']?verdict-([\S^>]+?)["']?>`)
var tagReg = regexp.MustCompile(`<[\s\S]*?>`)

func prepareVerdictFormats() (x map[string]string) {
	// From https://sta.codeforces.com/s/52452/js/preparedVerdictFormats-en.js
	x = map[string]string{}
	for key, val := range map[string]string {
		"30000": "<span class='verdict-failed'>Denial of judgement</span>",
		"30001": "<span class='verdict-failed'>Denial of judgement</span>",
		"30010": "<span class='verdict-failed'>Denial of judgement</span>",
		"30011": "<span class='verdict-failed'>Denial of judgement</span>",
		"30020": "<span class='verdict-failed'>Denial of judgement</span>",
		"30021": "<span class='verdict-failed'>Denial of judgement</span>",
		"30110": "<span class='verdict-failed'>Denial of judgement</span>",
		"30111": "<span class='verdict-failed'>Denial of judgement</span>",
		"30120": "<span class='verdict-failed'>Denial of judgement</span>",
		"30121": "<span class='verdict-failed'>Denial of judgement</span>",
		"30220": "<span class='verdict-failed'>Denial of judgement</span>",
		"30221": "<span class='verdict-failed'>Denial of judgement</span>",
		"31000": "<span class='verdict-accepted'>Pretests and hacks passed</span>",
		"31001": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"31010": "<span class='verdict-accepted'>Pretests and hacks passed</span>",
		"31011": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"31020": "<span class='verdict-accepted'>Pretests and hacks passed</span>",
		"31021": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"31110": "<span class='verdict-accepted'>Pretests and hacks passed</span>",
		"31111": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"31120": "<span class='verdict-accepted'>Pretests and hacks passed</span>",
		"31121": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"31220": "<span class='verdict-accepted'>Pretests and hacks passed</span>",
		"31221": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"32000": "Partial (hacks)",
		"32001": "Partial result: <span class=verdict-format-points>1</span> points",
		"32010": "Partial: <span class=\"verdict-format-passed\">0</span> hacks ouf of <span class=\"verdict-format-judged\">1</span>",
		"32011": "Partial result: <span class=verdict-format-points>1</span> points",
		"32020": "Partial: <span class=\"verdict-format-passed\">0</span> hacks ouf of <span class=\"verdict-format-judged\">2</span>",
		"32021": "Partial result: <span class=verdict-format-points>1</span> points",
		"32110": "Partial: <span class=\"verdict-format-passed\">1</span> hacks ouf of <span class=\"verdict-format-judged\">1</span>",
		"32111": "Partial result: <span class=verdict-format-points>1</span> points",
		"32120": "Partial: <span class=\"verdict-format-passed\">1</span> hacks ouf of <span class=\"verdict-format-judged\">2</span>",
		"32121": "Partial result: <span class=verdict-format-points>1</span> points",
		"32220": "Partial: <span class=\"verdict-format-passed\">2</span> hacks ouf of <span class=\"verdict-format-judged\">2</span>",
		"32221": "Partial result: <span class=verdict-format-points>1</span> points",
		"33000": "Compilation error",
		"33001": "Compilation error",
		"33010": "Compilation error",
		"33011": "Compilation error",
		"33020": "Compilation error",
		"33021": "Compilation error",
		"33110": "Compilation error",
		"33111": "Compilation error",
		"33120": "Compilation error",
		"33121": "Compilation error",
		"33220": "Compilation error",
		"33221": "Compilation error",
		"34000": "<span class='verdict-rejected'>Runtime error on hack</span>",
		"34001": "<span class='verdict-rejected'>Runtime error on hack</span>",
		"34010": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"34011": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"34020": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"34021": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"34110": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"34111": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"34120": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"34121": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"34220": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"34221": "<span class='verdict-rejected'>Runtime error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"35000": "<span class='verdict-rejected'>Wrong answer on hack</span>",
		"35001": "<span class='verdict-rejected'>Wrong answer on hack</span>",
		"35010": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">1</span></span>",
		"35011": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">1</span></span>",
		"35020": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">2</span></span>",
		"35021": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">2</span></span>",
		"35110": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">1</span></span>",
		"35111": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">1</span></span>",
		"35120": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">2</span></span>",
		"35121": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">2</span></span>",
		"35220": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">2</span></span>",
		"35221": "<span class='verdict-rejected'>Wrong answer on hack <span class=\"verdict-format-judged\">2</span></span>",
		"36000": "<span class='verdict-rejected'>Presentation error on hack</span>",
		"36001": "<span class='verdict-rejected'>Presentation error on hack</span>",
		"36010": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"36011": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"36020": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"36021": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"36110": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"36111": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">1</span></span>",
		"36120": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"36121": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"36220": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"36221": "<span class='verdict-rejected'>Presentation error on hack <span class=\"verdict-format-judged\">2</span></span>",
		"37000": "<span class='verdict-rejected'>Time limit exceeded on hack</span>",
		"37001": "<span class='verdict-rejected'>Time limit exceeded on hack</span>",
		"37010": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"37011": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"37020": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"37021": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"37110": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"37111": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"37120": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"37121": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"37220": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"37221": "<span class='verdict-rejected'>Time limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"38000": "<span class='verdict-rejected'>Memory limit exceeded on hack</span>",
		"38001": "<span class='verdict-rejected'>Memory limit exceeded on hack</span>",
		"38010": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"38011": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"38020": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"38021": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"38110": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"38111": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"38120": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"38121": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"38220": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"38221": "<span class='verdict-rejected'>Memory limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"39000": "<span class='verdict-rejected'>Idleness limit exceeded on hack</span>",
		"39001": "<span class='verdict-rejected'>Idleness limit exceeded on hack</span>",
		"39010": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"39011": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"39020": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"39021": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"39110": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"39111": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">1</span></span>",
		"39120": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"39121": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"39220": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"39221": "<span class='verdict-rejected'>Idleness limit exceeded on hack <span class=\"verdict-format-judged\">2</span></span>",
		"310000": "<span class='verdict-rejected'>Security violated on hack</span>",
		"310001": "<span class='verdict-rejected'>Security violated on hack</span>",
		"310010": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">1</span></span>",
		"310011": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">1</span></span>",
		"310020": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">2</span></span>",
		"310021": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">2</span></span>",
		"310110": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">1</span></span>",
		"310111": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">1</span></span>",
		"310120": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">2</span></span>",
		"310121": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">2</span></span>",
		"310220": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">2</span></span>",
		"310221": "<span class='verdict-rejected'>Security violated on hack <span class=\"verdict-format-judged\">2</span></span>",
		"311000": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311001": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311010": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311011": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311020": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311021": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311110": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311111": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311120": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311121": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311220": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"311221": "<span class='verdict-failed'>Judgement crashed on hack</span>",
		"312000": "<span class='verdict-failed'>Input preparation failed on hack</span>",
		"312001": "<span class='verdict-failed'>Input preparation failed on hack</span>",
		"312010": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">1</span></span>",
		"312011": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">1</span></span>",
		"312020": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">2</span></span>",
		"312021": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">2</span></span>",
		"312110": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">1</span></span>",
		"312111": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">1</span></span>",
		"312120": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">2</span></span>",
		"312121": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">2</span></span>",
		"312220": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">2</span></span>",
		"312221": "<span class='verdict-failed'>Input preparation failed on hack <span class=\"verdict-format-judged\">2</span></span>",
		"313000": "<span class='verdict-failed'>Hacked</span>",
		"313001": "<span class='verdict-failed'>Hacked</span>",
		"313010": "<span class='verdict-failed'>Hacked</span>",
		"313011": "<span class='verdict-failed'>Hacked</span>",
		"313020": "<span class='verdict-failed'>Hacked</span>",
		"313021": "<span class='verdict-failed'>Hacked</span>",
		"313110": "<span class='verdict-failed'>Hacked</span>",
		"313111": "<span class='verdict-failed'>Hacked</span>",
		"313120": "<span class='verdict-failed'>Hacked</span>",
		"313121": "<span class='verdict-failed'>Hacked</span>",
		"313220": "<span class='verdict-failed'>Hacked</span>",
		"313221": "<span class='verdict-failed'>Hacked</span>",
		"314000": "Skipped",
		"314001": "Skipped",
		"314010": "Skipped",
		"314011": "Skipped",
		"314020": "Skipped",
		"314021": "Skipped",
		"314110": "Skipped",
		"314111": "Skipped",
		"314120": "Skipped",
		"314121": "Skipped",
		"314220": "Skipped",
		"314221": "Skipped",
		"315000": "<span class='verdict-waiting'>Running on hack</span>",
		"315001": "<span class='verdict-waiting'>Running on hack</span>",
		"315010": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">1</span></span>",
		"315011": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">1</span></span>",
		"315020": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">2</span></span>",
		"315021": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">2</span></span>",
		"315110": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">1</span></span>",
		"315111": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">1</span></span>",
		"315120": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">2</span></span>",
		"315121": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">2</span></span>",
		"315220": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">2</span></span>",
		"315221": "<span class='verdict-waiting'>Running on hack <span class=\"verdict-format-judged\">2</span></span>",
		"316000": "<span class='verdict-rejected'>Rejected on hack</span>",
		"316001": "<span class='verdict-rejected'>Rejected on hack</span>",
		"316010": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">1</span></span>",
		"316011": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">1</span></span>",
		"316020": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">2</span></span>",
		"316021": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">2</span></span>",
		"316110": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">1</span></span>",
		"316111": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">1</span></span>",
		"316120": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">2</span></span>",
		"316121": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">2</span></span>",
		"316220": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">2</span></span>",
		"316221": "<span class='verdict-rejected'>Rejected on hack <span class=\"verdict-format-judged\">2</span></span>",
		"317000": "StatusForChallenge::submitted",
		"317001": "StatusForChallenge::submitted",
		"317010": "StatusForChallenge::submitted 1 tests / =1",
		"317011": "StatusForChallenge::submitted 1 tests / =1",
		"317020": "StatusForChallenge::submitted 2 tests / 2-4",
		"317021": "StatusForChallenge::submitted 2 tests / 2-4",
		"317110": "StatusForChallenge::submitted 1 tests / =1",
		"317111": "StatusForChallenge::submitted 1 tests / =1",
		"317120": "StatusForChallenge::submitted 2 tests / 2-4",
		"317121": "StatusForChallenge::submitted 2 tests / 2-4",
		"317220": "StatusForChallenge::submitted 2 tests / 2-4",
		"317221": "StatusForChallenge::submitted 2 tests / 2-4",
		"3-000": "<span class='verdict-waiting'>In queue</span>",
		"3-001": "<span class='verdict-waiting'>In queue</span>",
		"3-010": "<span class='verdict-waiting'>In queue</span>",
		"3-011": "<span class='verdict-waiting'>In queue</span>",
		"3-020": "<span class='verdict-waiting'>In queue</span>",
		"3-021": "<span class='verdict-waiting'>In queue</span>",
		"3-110": "<span class='verdict-waiting'>In queue</span>",
		"3-111": "<span class='verdict-waiting'>In queue</span>",
		"3-120": "<span class='verdict-waiting'>In queue</span>",
		"3-121": "<span class='verdict-waiting'>In queue</span>",
		"3-220": "<span class='verdict-waiting'>In queue</span>",
		"3-221": "<span class='verdict-waiting'>In queue</span>",
		"10000": "<span class='verdict-failed'>Judgement Failed</span>",
		"10001": "<span class='verdict-failed'>Judgement Failed</span>",
		"10010": "<span class='verdict-failed'>Judgement Failed</span>",
		"10011": "<span class='verdict-failed'>Judgement Failed</span>",
		"10020": "<span class='verdict-failed'>Judgement Failed</span>",
		"10021": "<span class='verdict-failed'>Judgement Failed</span>",
		"10110": "<span class='verdict-failed'>Judgement Failed</span>",
		"10111": "<span class='verdict-failed'>Judgement Failed</span>",
		"10120": "<span class='verdict-failed'>Judgement Failed</span>",
		"10121": "<span class='verdict-failed'>Judgement Failed</span>",
		"10220": "<span class='verdict-failed'>Judgement Failed</span>",
		"10221": "<span class='verdict-failed'>Judgement Failed</span>",
		"11000": "<span class='verdict-accepted'>Pretests passed</span>",
		"11001": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"11010": "<span class='verdict-accepted'>Pretests passed</span>",
		"11011": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"11020": "<span class='verdict-accepted'>Pretests passed</span>",
		"11021": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"11110": "<span class='verdict-accepted'>Pretests passed</span>",
		"11111": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"11120": "<span class='verdict-accepted'>Pretests passed</span>",
		"11121": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"11220": "<span class='verdict-accepted'>Pretests passed</span>",
		"11221": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"12000": "Partial (pretests)",
		"12001": "Partial result: <span class=verdict-format-points>1</span> points",
		"12010": "Partial: <span class=\"verdict-format-passed\">0</span> pretests out of <span class=\"verdict-format-judged\">1</span>",
		"12011": "Partial result: <span class=verdict-format-points>1</span> points",
		"12020": "Partial: <span class=\"verdict-format-passed\">0</span> pretests out of <span class=\"verdict-format-judged\">2</span>",
		"12021": "Partial result: <span class=verdict-format-points>1</span> points",
		"12110": "Partial: <span class=\"verdict-format-passed\">1</span> pretests out of <span class=\"verdict-format-judged\">1</span>",
		"12111": "Partial result: <span class=verdict-format-points>1</span> points",
		"12120": "Partial: <span class=\"verdict-format-passed\">1</span> pretests out of <span class=\"verdict-format-judged\">2</span>",
		"12121": "Partial result: <span class=verdict-format-points>1</span> points",
		"12220": "Partial: <span class=\"verdict-format-passed\">2</span> pretests out of <span class=\"verdict-format-judged\">2</span>",
		"12221": "Partial result: <span class=verdict-format-points>1</span> points",
		"13000": "Compilation error",
		"13001": "Compilation error",
		"13010": "Compilation error",
		"13011": "Compilation error",
		"13020": "Compilation error",
		"13021": "Compilation error",
		"13110": "Compilation error",
		"13111": "Compilation error",
		"13120": "Compilation error",
		"13121": "Compilation error",
		"13220": "Compilation error",
		"13221": "Compilation error",
		"14000": "<span class='verdict-rejected'>Runtime error on pretest</span>",
		"14001": "<span class='verdict-rejected'>Runtime error on pretest</span>",
		"14010": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"14011": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"14020": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"14021": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"14110": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"14111": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"14120": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"14121": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"14220": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"14221": "<span class='verdict-rejected'>Runtime error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"15000": "<span class='verdict-rejected'>Wrong answer on pretest</span>",
		"15001": "<span class='verdict-rejected'>Wrong answer on pretest</span>",
		"15010": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"15011": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"15020": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"15021": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"15110": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"15111": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"15120": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"15121": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"15220": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"15221": "<span class='verdict-rejected'>Wrong answer on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"16000": "<span class='verdict-rejected'>Presentation error on pretest</span>",
		"16001": "<span class='verdict-rejected'>Presentation error on pretest</span>",
		"16010": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"16011": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"16020": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"16021": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"16110": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"16111": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"16120": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"16121": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"16220": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"16221": "<span class='verdict-rejected'>Presentation error on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"17000": "<span class='verdict-rejected'>Time limit exceeded on pretest</span>",
		"17001": "<span class='verdict-rejected'>Time limit exceeded on pretest</span>",
		"17010": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"17011": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"17020": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"17021": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"17110": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"17111": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"17120": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"17121": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"17220": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"17221": "<span class='verdict-rejected'>Time limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"18000": "<span class='verdict-rejected'>Memory limit exceeded on pretest</span>",
		"18001": "<span class='verdict-rejected'>Memory limit exceeded on pretest</span>",
		"18010": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"18011": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"18020": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"18021": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"18110": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"18111": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"18120": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"18121": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"18220": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"18221": "<span class='verdict-rejected'>Memory limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"19000": "<span class='verdict-rejected'>Idleness limit exceeded on pretest</span>",
		"19001": "<span class='verdict-rejected'>Idleness limit exceeded on pretest</span>",
		"19010": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"19011": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"19020": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"19021": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"19110": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"19111": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"19120": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"19121": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"19220": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"19221": "<span class='verdict-rejected'>Idleness limit exceeded on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"110000": "<span class='verdict-rejected'>Security violated on pretest</span>",
		"110001": "<span class='verdict-rejected'>Security violated on pretest</span>",
		"110010": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"110011": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"110020": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"110021": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"110110": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"110111": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"110120": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"110121": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"110220": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"110221": "<span class='verdict-rejected'>Security violated on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"111000": "<span class='verdict-failed'>Denial of judgement</span>",
		"111001": "<span class='verdict-failed'>Denial of judgement</span>",
		"111010": "<span class='verdict-failed'>Denial of judgement</span>",
		"111011": "<span class='verdict-failed'>Denial of judgement</span>",
		"111020": "<span class='verdict-failed'>Denial of judgement</span>",
		"111021": "<span class='verdict-failed'>Denial of judgement</span>",
		"111110": "<span class='verdict-failed'>Denial of judgement</span>",
		"111111": "<span class='verdict-failed'>Denial of judgement</span>",
		"111120": "<span class='verdict-failed'>Denial of judgement</span>",
		"111121": "<span class='verdict-failed'>Denial of judgement</span>",
		"111220": "<span class='verdict-failed'>Denial of judgement</span>",
		"111221": "<span class='verdict-failed'>Denial of judgement</span>",
		"112000": "<span class='verdict-failed'>Input preparation failed on pretest</span>",
		"112001": "<span class='verdict-failed'>Input preparation failed on pretest</span>",
		"112010": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"112011": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"112020": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"112021": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"112110": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"112111": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"112120": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"112121": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"112220": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"112221": "<span class='verdict-failed'>Input preparation failed on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"113000": "<span class='verdict-failed'>Hacked</span>",
		"113001": "<span class='verdict-failed'>Hacked</span>",
		"113010": "<span class='verdict-failed'>Hacked</span>",
		"113011": "<span class='verdict-failed'>Hacked</span>",
		"113020": "<span class='verdict-failed'>Hacked</span>",
		"113021": "<span class='verdict-failed'>Hacked</span>",
		"113110": "<span class='verdict-failed'>Hacked</span>",
		"113111": "<span class='verdict-failed'>Hacked</span>",
		"113120": "<span class='verdict-failed'>Hacked</span>",
		"113121": "<span class='verdict-failed'>Hacked</span>",
		"113220": "<span class='verdict-failed'>Hacked</span>",
		"113221": "<span class='verdict-failed'>Hacked</span>",
		"114000": "Skipped",
		"114001": "Skipped",
		"114010": "Skipped",
		"114011": "Skipped",
		"114020": "Skipped",
		"114021": "Skipped",
		"114110": "Skipped",
		"114111": "Skipped",
		"114120": "Skipped",
		"114121": "Skipped",
		"114220": "Skipped",
		"114221": "Skipped",
		"115000": "<span class='verdict-waiting'>Running on pretest</span>",
		"115001": "<span class='verdict-waiting'>Running on pretest</span>",
		"115010": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"115011": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"115020": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"115021": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"115110": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"115111": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"115120": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"115121": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"115220": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"115221": "<span class='verdict-waiting'>Running on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"116000": "<span class='verdict-rejected'>Rejected on pretest</span>",
		"116001": "<span class='verdict-rejected'>Rejected on pretest</span>",
		"116010": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"116011": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"116020": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"116021": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"116110": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"116111": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">1</span></span>",
		"116120": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"116121": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"116220": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"116221": "<span class='verdict-rejected'>Rejected on pretest <span class=\"verdict-format-judged\">2</span></span>",
		"117000": "StatusForPretest::submitted",
		"117001": "StatusForPretest::submitted",
		"117010": "StatusForPretest::submitted 1 tests / =1",
		"117011": "StatusForPretest::submitted 1 tests / =1",
		"117020": "StatusForPretest::submitted 2 tests / 2-4",
		"117021": "StatusForPretest::submitted 2 tests / 2-4",
		"117110": "StatusForPretest::submitted 1 tests / =1",
		"117111": "StatusForPretest::submitted 1 tests / =1",
		"117120": "StatusForPretest::submitted 2 tests / 2-4",
		"117121": "StatusForPretest::submitted 2 tests / 2-4",
		"117220": "StatusForPretest::submitted 2 tests / 2-4",
		"117221": "StatusForPretest::submitted 2 tests / 2-4",
		"1-000": "<span class='verdict-waiting'>In queue</span>",
		"1-001": "<span class='verdict-waiting'>In queue</span>",
		"1-010": "<span class='verdict-waiting'>In queue</span>",
		"1-011": "<span class='verdict-waiting'>In queue</span>",
		"1-020": "<span class='verdict-waiting'>In queue</span>",
		"1-021": "<span class='verdict-waiting'>In queue</span>",
		"1-110": "<span class='verdict-waiting'>In queue</span>",
		"1-111": "<span class='verdict-waiting'>In queue</span>",
		"1-120": "<span class='verdict-waiting'>In queue</span>",
		"1-121": "<span class='verdict-waiting'>In queue</span>",
		"1-220": "<span class='verdict-waiting'>In queue</span>",
		"1-221": "<span class='verdict-waiting'>In queue</span>",
		"20000": "<span class='verdict-failed'>Judgement failed</span>",
		"20001": "<span class='verdict-failed'>Judgement failed</span>",
		"20010": "<span class='verdict-failed'>Judgement failed</span>",
		"20011": "<span class='verdict-failed'>Judgement failed</span>",
		"20020": "<span class='verdict-failed'>Judgement failed</span>",
		"20021": "<span class='verdict-failed'>Judgement failed</span>",
		"20110": "<span class='verdict-failed'>Judgement failed</span>",
		"20111": "<span class='verdict-failed'>Judgement failed</span>",
		"20120": "<span class='verdict-failed'>Judgement failed</span>",
		"20121": "<span class='verdict-failed'>Judgement failed</span>",
		"20220": "<span class='verdict-failed'>Judgement failed</span>",
		"20221": "<span class='verdict-failed'>Judgement failed</span>",
		"21000": "<span class='verdict-accepted'>Accepted</span>",
		"21001": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"21010": "<span class='verdict-accepted'>Accepted</span>",
		"21011": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"21020": "<span class='verdict-accepted'>Accepted</span>",
		"21021": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"21110": "<span class='verdict-accepted'>Accepted</span>",
		"21111": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"21120": "<span class='verdict-accepted'>Accepted</span>",
		"21121": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"21220": "<span class='verdict-accepted'>Accepted</span>",
		"21221": "<span class='verdict-accepted'>Perfect result: <span class=verdict-format-points>1</span> points</span>",
		"22000": "Partial",
		"22001": "Partial result: <span class=verdict-format-points>1</span> points",
		"22010": "Partial: <span class=\"verdict-format-passed\">0</span> tests out of <span class=\"verdict-format-judged\">1</span>",
		"22011": "Partial result: <span class=verdict-format-points>1</span> points",
		"22020": "Partial: <span class=\"verdict-format-passed\">0</span> tests out of <span class=\"verdict-format-judged\">2</span>",
		"22021": "Partial result: <span class=verdict-format-points>1</span> points",
		"22110": "Partial: <span class=\"verdict-format-passed\">1</span> tests out of <span class=\"verdict-format-judged\">1</span>",
		"22111": "Partial result: <span class=verdict-format-points>1</span> points",
		"22120": "Partial: <span class=\"verdict-format-passed\">1</span> tests out of <span class=\"verdict-format-judged\">2</span>",
		"22121": "Partial result: <span class=verdict-format-points>1</span> points",
		"22220": "Partial: <span class=\"verdict-format-passed\">2</span> tests out of <span class=\"verdict-format-judged\">2</span>",
		"22221": "Partial result: <span class=verdict-format-points>1</span> points",
		"23000": "Compilation error",
		"23001": "Compilation error",
		"23010": "Compilation error",
		"23011": "Compilation error",
		"23020": "Compilation error",
		"23021": "Compilation error",
		"23110": "Compilation error",
		"23111": "Compilation error",
		"23120": "Compilation error",
		"23121": "Compilation error",
		"23220": "Compilation error",
		"23221": "Compilation error",
		"24000": "<span class='verdict-rejected'>Runtime error</span>",
		"24001": "<span class='verdict-rejected'>Runtime error</span>",
		"24010": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">1</span></span>",
		"24011": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">1</span></span>",
		"24020": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">2</span></span>",
		"24021": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">2</span></span>",
		"24110": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">1</span></span>",
		"24111": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">1</span></span>",
		"24120": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">2</span></span>",
		"24121": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">2</span></span>",
		"24220": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">2</span></span>",
		"24221": "<span class='verdict-rejected'>Runtime error on test <span class=\"verdict-format-judged\">2</span></span>",
		"25000": "<span class='verdict-rejected'>Wrong answer</span>",
		"25001": "<span class='verdict-rejected'>Wrong answer</span>",
		"25010": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">1</span></span>",
		"25011": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">1</span></span>",
		"25020": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">2</span></span>",
		"25021": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">2</span></span>",
		"25110": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">1</span></span>",
		"25111": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">1</span></span>",
		"25120": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">2</span></span>",
		"25121": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">2</span></span>",
		"25220": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">2</span></span>",
		"25221": "<span class='verdict-rejected'>Wrong answer on test <span class=\"verdict-format-judged\">2</span></span>",
		"26000": "<span class='verdict-rejected'>Presentation error</span>",
		"26001": "<span class='verdict-rejected'>Presentation error</span>",
		"26010": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">1</span></span>",
		"26011": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">1</span></span>",
		"26020": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">2</span></span>",
		"26021": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">2</span></span>",
		"26110": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">1</span></span>",
		"26111": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">1</span></span>",
		"26120": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">2</span></span>",
		"26121": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">2</span></span>",
		"26220": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">2</span></span>",
		"26221": "<span class='verdict-rejected'>Presentation error on test <span class=\"verdict-format-judged\">2</span></span>",
		"27000": "<span class='verdict-rejected'>Time limit exceeded</span>",
		"27001": "<span class='verdict-rejected'>Time limit exceeded</span>",
		"27010": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"27011": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"27020": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"27021": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"27110": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"27111": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"27120": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"27121": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"27220": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"27221": "<span class='verdict-rejected'>Time limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"28000": "<span class='verdict-rejected'>Memory limit exceeded</span>",
		"28001": "<span class='verdict-rejected'>Memory limit exceeded</span>",
		"28010": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"28011": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"28020": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"28021": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"28110": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"28111": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"28120": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"28121": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"28220": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"28221": "<span class='verdict-rejected'>Memory limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"29000": "<span class='verdict-rejected'>Idleness limit exceeded</span>",
		"29001": "<span class='verdict-rejected'>Idleness limit exceeded</span>",
		"29010": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"29011": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"29020": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"29021": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"29110": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"29111": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">1</span></span>",
		"29120": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"29121": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"29220": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"29221": "<span class='verdict-rejected'>Idleness limit exceeded on test <span class=\"verdict-format-judged\">2</span></span>",
		"210000": "<span class='verdict-rejected'>Security violated</span>",
		"210001": "<span class='verdict-rejected'>Security violated</span>",
		"210010": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">1</span></span>",
		"210011": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">1</span></span>",
		"210020": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">2</span></span>",
		"210021": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">2</span></span>",
		"210110": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">1</span></span>",
		"210111": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">1</span></span>",
		"210120": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">2</span></span>",
		"210121": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">2</span></span>",
		"210220": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">2</span></span>",
		"210221": "<span class='verdict-rejected'>Security violated on test <span class=\"verdict-format-judged\">2</span></span>",
		"211000": "<span class='verdict-failed'>Denial of judgement</span>",
		"211001": "<span class='verdict-failed'>Denial of judgement</span>",
		"211010": "<span class='verdict-failed'>Denial of judgement</span>",
		"211011": "<span class='verdict-failed'>Denial of judgement</span>",
		"211020": "<span class='verdict-failed'>Denial of judgement</span>",
		"211021": "<span class='verdict-failed'>Denial of judgement</span>",
		"211110": "<span class='verdict-failed'>Denial of judgement</span>",
		"211111": "<span class='verdict-failed'>Denial of judgement</span>",
		"211120": "<span class='verdict-failed'>Denial of judgement</span>",
		"211121": "<span class='verdict-failed'>Denial of judgement</span>",
		"211220": "<span class='verdict-failed'>Denial of judgement</span>",
		"211221": "<span class='verdict-failed'>Denial of judgement</span>",
		"212000": "<span class='verdict-failed'>Input preparation failed</span>",
		"212001": "<span class='verdict-failed'>Input preparation failed</span>",
		"212010": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">1</span></span>",
		"212011": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">1</span></span>",
		"212020": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">2</span></span>",
		"212021": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">2</span></span>",
		"212110": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">1</span></span>",
		"212111": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">1</span></span>",
		"212120": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">2</span></span>",
		"212121": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">2</span></span>",
		"212220": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">2</span></span>",
		"212221": "<span class='verdict-failed'>Input preparation failed on test <span class=\"verdict-format-judged\">2</span></span>",
		"213000": "<span class='verdict-failed'>Hacked</span>",
		"213001": "<span class='verdict-failed'>Hacked</span>",
		"213010": "<span class='verdict-failed'>Hacked</span>",
		"213011": "<span class='verdict-failed'>Hacked</span>",
		"213020": "<span class='verdict-failed'>Hacked</span>",
		"213021": "<span class='verdict-failed'>Hacked</span>",
		"213110": "<span class='verdict-failed'>Hacked</span>",
		"213111": "<span class='verdict-failed'>Hacked</span>",
		"213120": "<span class='verdict-failed'>Hacked</span>",
		"213121": "<span class='verdict-failed'>Hacked</span>",
		"213220": "<span class='verdict-failed'>Hacked</span>",
		"213221": "<span class='verdict-failed'>Hacked</span>",
		"214000": "Skipped",
		"214001": "Skipped",
		"214010": "Skipped",
		"214011": "Skipped",
		"214020": "Skipped",
		"214021": "Skipped",
		"214110": "Skipped",
		"214111": "Skipped",
		"214120": "Skipped",
		"214121": "Skipped",
		"214220": "Skipped",
		"214221": "Skipped",
		"215000": "<span class='verdict-waiting'>Running</span>",
		"215001": "<span class='verdict-waiting'>Running</span>",
		"215010": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">1</span></span>",
		"215011": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">1</span></span>",
		"215020": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">2</span></span>",
		"215021": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">2</span></span>",
		"215110": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">1</span></span>",
		"215111": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">1</span></span>",
		"215120": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">2</span></span>",
		"215121": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">2</span></span>",
		"215220": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">2</span></span>",
		"215221": "<span class='verdict-waiting'>Running on test <span class=\"verdict-format-judged\">2</span></span>",
		"216000": "<span class='verdict-rejected'>Rejected</span>",
		"216001": "<span class='verdict-rejected'>Rejected</span>",
		"216010": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">1</span></span>",
		"216011": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">1</span></span>",
		"216020": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">2</span></span>",
		"216021": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">2</span></span>",
		"216110": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">1</span></span>",
		"216111": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">1</span></span>",
		"216120": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">2</span></span>",
		"216121": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">2</span></span>",
		"216220": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">2</span></span>",
		"216221": "<span class='verdict-rejected'>Rejected on test <span class=\"verdict-format-judged\">2</span></span>",
		"217000": "Pending judgement",
		"217001": "Pending judgement",
		"217010": "Pending judgement of 1 test",
		"217011": "Pending judgement of 1 test",
		"217020": "Pending judgement of 2 tests",
		"217021": "Pending judgement of 2 tests",
		"217110": "Pending judgement of 1 test",
		"217111": "Pending judgement of 1 test",
		"217120": "Pending judgement of 2 tests",
		"217121": "Pending judgement of 2 tests",
		"217220": "Pending judgement of 2 tests",
		"217221": "Pending judgement of 2 tests",
		"2-000": "<span class='verdict-waiting'>In queue</span>",
		"2-001": "<span class='verdict-waiting'>In queue</span>",
		"2-010": "<span class='verdict-waiting'>In queue</span>",
		"2-011": "<span class='verdict-waiting'>In queue</span>",
		"2-020": "<span class='verdict-waiting'>In queue</span>",
		"2-021": "<span class='verdict-waiting'>In queue</span>",
		"2-110": "<span class='verdict-waiting'>In queue</span>",
		"2-111": "<span class='verdict-waiting'>In queue</span>",
		"2-120": "<span class='verdict-waiting'>In queue</span>",
		"2-121": "<span class='verdict-waiting'>In queue</span>",
		"2-220": "<span class='verdict-waiting'>In queue</span>",
		"2-221": "<span class='verdict-waiting'>In queue</span>",
	} {
		val = fmtReg.ReplaceAllString(val, `${f-$1}`)
		val = colReg.ReplaceAllString(val, `${c-$1}`)
		val = tagReg.ReplaceAllString(val, "")
		val = strings.TrimSpace(val)
		x[key] = val
	}
	return
}

var PreparedVerdictFormats = prepareVerdictFormats()
